Create Database DB_TASKS
use DB_TASKS
GO
Create table TB_TASKS  (
	CD_TASKS int IDENTITY NOT NULL,
	NM_TITLE VARCHAR(250) NOT NULL,
	DS_TASK VARCHAR(MAX) NOT NULL,
	FL_TASK_COMPLETED BIT NOT NULL,
	DT_TASK_CREATION DATETIME NOT NULL,
)
